Used car sales analysis

Running my imports for Pandas, different models, my scaler, splitting the data, and matplot lib for doing data visualization

In [91]:
import numpy as np
import scipy.stats as stats
import sklearn
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
import seaborn as sns
from matplotlib.ticker import FuncFormatter
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV

Looking at the organization of my files with ls

In [92]:
ls

data/  README.md  Untitled.ipynb

Loading in the data file as a data frame with pandas

In [93]:
df = pd.read_csv('data/archive/FINAL_SPINNY_900.csv')

Looking at a preview of the data

In [94]:
df.head()

,Car_Name,Make,Model,Make_Year,Color,Body_Type,Mileage_Run,No_of_Owners,Seating_Capacity,Fuel_Type,Fuel_Tank_Capacity(L),Engine_Type,CC_Displacement,Transmission,Transmission_Type,Power(BHP),Torque(Nm),Mileage(kmpl),Emission,Price
0,Volkswagen Ameo [2016-2017] Highline 1.5L AT (D),Volkswagen,Ameo,2017,silver,sedan,44611,1st,5,diesel,45,1.5L TDI Engine,1498,7-Speed,Automatic,109.00,250.00,21.66,BS IV,"6,57,000"
1,Hyundai i20 Active [2015-2020] 1.2 SX,Hyundai,i20 Active,2016,red,crossover,20305,1st,5,petrol,45,1.2L Kappa 5 Speed Manual Transmission,1197,5-Speed,Manual,82.00,115.00,17.19,BS V,"6,82,000"
2,Honda WR-V VX i-VTEC,Honda,WR-V,2019,white,suv,29540,2nd,5,petrol,40,i-VTEC Petrol engine,1199,5-Speed,Manual,88.50,110.00,16.50,BS IV,"7,93,000"
3,Renault Kwid 1.0 RXT AMT,Renault,Kwid,2017,bronze,hatchback,35680,1st,5,petrol,28,1.0L,999,5-Speed,Manual,67.00,91.00,21.70,BS IV,"4,14,000"
4,Hyundai Grand i10 [2017-2020] Asta 1.2 Kappa VTVT,Hyundai,Grand i10,2017,orange,hatchback,25126,1st,5,petrol,43,Kappa VTVT Petrol Engine,1197,5-Speed,Manual,81.86,113.75,18.90,BS V,"5,15,000"

Looking at Emission values to potentialy change the to numerical values (int)

In [95]:
df["Emission"].value_counts()

BS IV     588
BS V      303
BS III     82
Name: Emission, dtype: int64

Looking at the values in price column

In [96]:
df['Price'].values

array(['6,57,000', '6,82,000', '7,93,000', '4,14,000', '5,15,000',
       '6,04,000', '3,16,000', '14,19,000', '7,10,000', '3,92,000',
       '6,13,000', '5,98,000', '9,69,000', '21,00,000', '6,66,000',
       '10,39,000', '8,58,000', '8,60,000', '6,80,000', '6,25,000',
       '5,67,000', '3,71,000', '10,76,000', '5,87,000', '3,96,000',
       '5,54,000', '9,84,000', '5,07,000', '5,86,000', '6,39,000',
       '2,37,000', '5,36,000', '4,56,000', '11,07,000', '5,71,000',
       '5,87,000', '6,29,000', '7,18,000', '3,96,000', '8,77,000',
       '7,74,000', '5,54,000', '8,29,000', '5,30,000', '3,67,000',
       '5,50,000', '6,60,000', '9,98,000', '10,12,000', '15,37,000',
       '9,08,000', '5,08,000', '4,17,000', '7,25,000', '9,80,000',
       '7,96,000', '4,35,000', '5,54,000', '4,81,000', '4,42,000',
       '5,30,000', '7,59,000', '4,55,000', '19,72,000', '11,38,000',
       '9,20,000', '17,42,000', '5,68,000', '4,19,000', '4,76,000',
       '5,77,000', '5,41,000', '7,30,000', '18,75,000', '6,22,000',
       '9,37,000', '6,25,000', '6,09,000', '5,71,000', '4,12,000',
       '6,38,000', '8,07,000', '5,90,000', '6,51,000', '6,94,000',
       '13,64,000', '7,83,000', '6,28,000', '8,85,000', '7,24,000',
       '4,70,000', '10,85,000', '6,20,000', '6,59,000', '9,53,000',
       '11,73,000', '4,57,000', '4,61,000', '4,71,000', '9,02,000',
       '7,91,000', '5,06,000', '5,94,000', '3,62,000', '9,14,000',
       '5,44,000', '5,13,000', '7,37,000', '6,64,000', '10,27,000',
       '5,75,000', '8,42,000', '7,42,000', '10,71,000', '10,44,000',
       '6,39,000', '16,49,000', '3,92,000', '6,26,000', '3,20,000',
       '5,79,000', '6,08,000', '7,73,000', '6,15,000', '5,19,000',
       '8,69,000', '13,99,000', '3,56,000', '5,62,000', '5,22,000',
       '6,99,000', '5,10,000', '5,12,000', '6,58,000', '3,69,000',
       '9,66,000', '9,32,000', '3,88,000', '4,89,000', '9,26,000',
       '17,09,000', '10,39,000', '17,70,000', '11,63,000', '13,49,000',
       '17,05,000', '7,39,000', '6,00,000', '10,39,000', '9,50,000',
       '7,48,000', '8,20,000', '6,45,000', '5,70,000', '17,64,000',
       '6,77,000', '8,37,000', '18,26,000', '12,90,000', '15,59,000',
       '5,23,000', '9,42,000', '7,25,000', '7,11,000', '9,74,000',
       '6,08,000', '2,73,000', '3,04,000', '3,61,000', '3,65,000',
       '6,16,000', '6,90,000', '7,49,000', '6,19,000', '5,47,000',
       '5,79,000', '6,86,000', '6,79,000', '4,00,000', '6,12,000',
       '16,44,000', '3,42,000', '7,90,000', '3,60,000', '2,76,000',
       '3,52,000', '3,63,000', '3,33,000', '5,89,000', '7,35,000',
       '7,90,000', '11,17,000', '6,60,000', '6,78,000', '8,57,000',
       '4,83,000', '2,48,000', '15,00,000', '7,59,000', '3,36,000',
       '6,77,000', '7,11,000', '10,99,000', '10,99,000', '10,99,000',
       '10,99,000', '10,78,000', '3,48,000', '6,59,000', '5,01,000',
       '10,13,000', '17,41,000', '8,29,000', '4,96,000', '2,69,000',
       '9,27,000', '4,51,000', '5,32,000', '3,38,000', '10,32,000',
       '5,57,000', '6,53,000', '8,98,000', '9,12,000', '6,42,000',
       '6,51,000', '5,03,000', '3,30,000', '3,95,000', '12,35,000',
       '8,08,000', '4,58,000', '5,14,000', '5,12,000', '29,41,000',
       '13,46,000', '8,44,000', '8,44,000', '8,44,000', '8,44,000',
       '7,89,000', '5,70,000', '6,39,000', '4,70,000', '4,54,000',
       '6,18,000', '5,48,000', '7,10,000', '6,21,000', '12,90,000',
       '12,90,000', '12,90,000', '12,90,000', '7,48,000', '2,67,000',
       '3,68,000', '11,37,000', '6,99,000', '5,44,000', '9,82,000',
       '6,11,000', '9,41,000', '5,34,000', '5,84,000', '8,27,000',
       '6,81,000', '6,81,000', '6,81,000', '6,81,000', '5,80,000',
       '7,46,000', '4,52,000', '2,39,000', '4,53,000', '5,21,000',
       '7,80,000', '6,94,000', '6,98,000', '4,26,000', '9,89,000',
       '9,40,000', '5,56,000', '7,85,000', '10,77,000', '4,64,000',
       '5,89,000', '5,89,000', '5,89,000', '5,89,000', '5,74,000',
       '6,55,000', '9,20,000', '4,88,000', '5,48,000', '5,28,000',
       '5,27,000', '9,52,000', '3,40,000', '7,90,000', '7,90,000',
       '7,90,000', '7,90,000', '7,65,000', '4,20,000', '8,00,000',
       '4,86,000', '14,65,000', '3,48,000', '8,92,000', '4,51,000',
       '4,03,000', '3,38,000', '8,06,000', '6,34,000', '6,54,000',
       '8,82,000', '11,96,000', '6,69,000', '5,89,000', '19,12,000',
       '6,28,000', '8,12,000', '9,14,000', '11,12,000', '8,10,000',
       '5,30,000', '4,55,000', '4,98,000', '4,03,000', '3,80,000',
       '10,92,000', '10,92,000', '10,92,000', '10,92,000', '4,57,000',
       '8,13,000', '8,20,000', '5,02,000', '4,14,000', '3,91,000',
       '4,33,000', '3,72,000', '3,84,000', '7,84,000', '9,71,000',
       '6,55,000', '5,39,000', '4,70,000', '7,90,000', '4,15,000',
       '3,68,000', '4,57,000', '8,94,000', '3,38,000', '3,42,000',
       '9,86,000', '6,37,000', '6,88,000', '8,16,000', '6,44,000',
       '6,44,000', '6,44,000', '6,44,000', '10,86,000', '10,86,000',
       '10,86,000', '10,86,000', '6,74,000', '3,50,000', '12,13,000',
       '2,75,000', '5,33,000', '8,24,000', '8,05,000', '10,98,000',
       '7,95,000', '4,06,000', '7,20,000', '7,32,000', '4,06,000',
       '6,22,000', '7,42,000', '6,99,000', '4,26,000', '2,84,000',
       '5,74,000', '6,99,000', '6,05,000', '11,04,000', '4,51,000',
       '6,33,000', '18,48,000', '18,48,000', '18,48,000', '18,48,000',
       '9,43,000', '7,09,000', '4,02,000', '6,46,000', '3,34,000',
       '4,96,000', '7,35,000', '4,87,000', '4,10,000', '7,66,000',
       '16,47,000', '3,11,000', '3,91,000', '8,70,000', '3,23,000',
       '5,98,000', '5,89,000', '4,64,000', '7,02,000', '4,72,000',
       '3,53,000', '4,02,000', '9,77,000', '3,58,000', '3,99,000',
       '8,36,000', '8,03,000', '4,10,000', '7,95,000', '12,66,000',
       '3,43,000', '3,62,000', '3,00,000', '6,94,000', '4,84,000',
       '10,01,000', '3,84,000', '8,58,000', '4,82,000', '5,81,000',
       '3,20,000', '11,76,000', '12,74,000', '3,62,000', '4,89,000',
       '8,15,000', '10,64,000', '3,89,000', '7,15,000', '6,28,000',
       '3,17,000', '7,29,000', '3,96,000', '9,49,000', '4,53,000',
       '8,98,000', '2,81,000', '6,28,000', '7,13,000', '3,38,000',
       '4,45,000', '4,47,000', '6,20,000', '5,24,000', '10,47,000',
       '4,44,000', '9,06,000', '6,86,000', '3,72,000', '6,84,000',
       '3,52,000', '3,92,000', '4,89,000', '5,51,000', '6,88,000',
       '15,49,000', '7,10,000', '3,08,000', '8,48,000', '7,87,000',
       '6,38,000', '5,28,000', '6,06,000', '4,42,000', '8,59,000',
       '5,14,000', '6,63,000', '5,68,000', '4,07,000', '8,24,000',
       '7,39,000', '4,85,000', '14,64,000', '6,91,000', '5,12,000',
       '7,88,000', '4,57,000', '7,55,000', '12,77,000', '4,52,000',
       '3,01,000', '2,62,000', '3,08,000', '10,23,000', '6,35,000',
       '10,15,000', '2,55,000', '3,96,000', '10,11,000', '6,61,000',
       '4,50,000', '4,35,000', '7,72,000', '3,31,000', '8,30,000',
       '4,85,000', '4,05,000', '3,47,000', '3,69,000', '7,68,000',
       '5,78,000', '4,17,000', '3,49,000', '5,76,000', '6,29,000',
       '4,23,000', '6,43,000', '7,37,000', '4,25,000', '3,30,000',
       '13,69,000', '4,36,000', '8,83,000', '16,10,000', '4,00,000',
       '4,29,000', '4,08,000', '4,08,000', '7,39,000', '7,54,000',
       '7,54,000', '7,54,000', '7,54,000', '4,61,000', '7,32,000',
       '7,01,000', '4,06,000', '2,71,000', '2,93,000', '3,68,000',
       '4,47,000', '9,12,000', '3,87,000', '4,48,000', '10,51,000',
       '10,51,000', '10,51,000', '10,51,000', '9,14,000', '9,14,000',
       '9,14,000', '9,14,000', '5,98,000', '18,22,000', '18,22,000',
       '18,22,000', '18,22,000', '15,89,000', '10,27,000', '10,27,000',
       '10,27,000', '10,27,000', '8,63,000', '3,15,000', '4,33,000',
       '4,54,000', '8,07,000', '7,34,000', '10,54,000', '4,49,000',
       '5,38,000', '8,83,000', '5,44,000', '4,85,000', '9,95,000',
       '7,52,000', '2,66,000', '5,51,000', '4,77,000', '5,23,000',
       '14,22,000', '4,30,000', '8,94,000', '8,94,000', '8,94,000',
       '8,94,000', '17,00,000', '9,14,000', '9,71,000', '5,93,000',
       '4,99,000', '7,28,000', '2,87,000', '3,73,000', '4,04,000',
       '3,18,000', '7,27,000', '4,47,000', '11,50,000', '6,05,000',
       '11,17,000', '5,06,000', '6,10,000', '2,90,000', '5,42,000',
       '17,20,000', '5,23,000', '7,45,000', '10,52,000', '8,54,000',
       '7,88,000', '4,60,000', '6,89,000', '6,38,000', '14,58,000',
       '8,14,000', '17,74,000', '4,55,000', '3,14,000', '20,19,000',
       '20,19,000', '20,19,000', '20,19,000', '8,76,000', '4,23,000',
       '4,23,000', '4,23,000', '4,23,000', '11,00,000', '4,11,000',
       '3,40,000', '4,05,000', '7,38,000', '3,65,000', '17,00,000',
       '4,22,000', '19,58,000', '19,58,000', '19,58,000', '19,58,000',
       '10,19,000', '19,78,000', '19,78,000', '19,78,000', '19,78,000',
       '4,12,000', '8,78,000', '4,29,000', '7,08,000', '6,78,000',
       '3,26,000', '3,36,000', '15,89,000', '3,35,000', '3,68,000',
       '4,39,000', '10,66,000', '19,84,000', '19,84,000', '19,84,000',
       '19,84,000', '3,28,000', '10,55,000', '5,55,000', '4,34,000',
       '3,48,000', '5,56,000', '4,47,000', '5,69,000', '4,28,000',
       '4,55,000', '11,64,000', '11,78,000', '7,65,000', '8,85,000',
       '6,58,000', '12,40,000', '7,52,000', '8,69,000', '8,69,000',
       '8,69,000', '8,69,000', '8,33,000', '11,71,000', '8,40,000',
       '7,06,000', '2,73,000', '6,03,000', '5,21,000', '7,64,000',
       '12,66,000', '10,30,000', '5,11,000', '3,89,000', '11,37,000',
       '5,63,000', '4,65,000', '17,08,000', '7,51,000', '3,06,000',
       '3,06,000', '3,06,000', '3,06,000', '7,71,000', '8,23,000',
       '9,80,000', '5,71,000', '6,14,000', '8,43,000', '4,10,000',
       '4,27,000', '4,84,000', '6,22,000', '4,23,000', '8,12,000',
       '5,49,000', '5,25,000', '7,09,000', '7,44,000', '9,82,000',
       '8,81,000', '8,34,000', '9,16,000', '8,80,000', '8,71,000',
       '5,94,000', '13,66,000', '7,85,000', '7,85,000', '7,85,000',
       '7,85,000', '7,18,000', '7,49,000', '3,20,000', '8,60,000',
       '7,99,000', '6,25,000', '4,11,000', '5,40,000', '8,22,000',
       '7,84,000', '11,65,000', '3,96,000', '7,70,000', '5,15,000',
       '4,26,000', '5,41,000', '3,90,000', '8,10,000', '9,32,000',
       '7,92,000', '12,38,000', '7,69,000', '6,35,000', '4,81,000',
       '11,85,000', '4,66,000', '4,89,000', '14,54,000', '10,32,000',
       '8,47,000', '8,47,000', '8,47,000', '8,47,000', '14,11,000',
       '5,59,000', '6,25,000', '9,99,000', '6,77,000', '4,95,000',
       '7,61,000', '6,47,000', '8,77,000', '7,34,000', '6,61,000',
       '4,46,000', '8,14,000', '3,91,000', '10,34,000', '3,50,000',
       '7,63,000', '4,87,000', '7,87,000', '7,87,000', '7,87,000',
       '7,87,000', '5,26,000', '5,71,000', '10,11,000', '10,11,000',
       '10,11,000', '10,11,000', '6,99,000', '7,26,000', '5,17,000',
       '5,73,000', '4,54,000', '6,25,000', '9,55,000', '2,74,000',
       '9,26,000', '4,65,000', '6,63,000', '8,12,000', '8,12,000',
       '8,12,000', '8,12,000', '8,96,000', '9,78,000', '5,41,000',
       '11,06,000', '4,64,000', '9,94,000', '8,09,000', '5,44,000',
       '5,38,000', '6,07,000', '7,54,000', '6,18,000', '8,14,000',
       '4,06,000', '9,97,000', '5,23,000', '4,25,000', '10,26,000',
       '3,53,000', '4,90,000', '8,62,000', '4,25,000', '5,48,000',
       '4,65,000', '5,05,000', '11,66,000', '10,99,000', '4,59,000',
       '5,06,000', '6,18,000', '5,44,000', '3,34,000', '7,64,000',
       '2,45,000', '2,90,000', '10,91,000', '4,70,000', '4,30,000',
       '4,30,000', '7,49,000', '5,29,000', '7,22,000', '2,79,000',
       '6,20,000', '11,30,000', '10,43,000', '4,01,000', '3,35,000',
       '9,15,000', '5,28,000', '7,85,000', '7,00,000', '4,39,000',
       '3,19,000', '5,20,000', '4,99,000', '6,62,000', '9,36,000',
       '7,37,000', '4,39,000', '4,39,000', '4,39,000', '4,39,000',
       '5,43,000', '6,89,000', '4,95,000', '6,17,000', '4,69,000',
       '6,69,000', '6,69,000', '6,69,000', '6,69,000', '7,52,000',
       '11,32,000', '7,60,000', '3,67,000', '5,68,000', '14,48,000',
       '5,79,000', '4,75,000', '6,35,000', '6,47,000', '13,14,000',
       '3,26,000', '11,27,000', '5,65,000', '5,53,000', '8,31,000',
       '7,76,000', '5,33,000', '4,43,000', '5,24,000', '12,99,000',
       '4,20,000', '4,50,000', '12,12,000', '7,72,000', '16,99,000',
       '6,12,000', '9,11,000', '7,07,000', '10,98,000', '3,35,000',
       '5,45,000', '4,75,000', '6,67,000', '1,88,000', '9,07,000',
       '6,19,000', '7,48,000', '7,31,000', '3,95,000', '7,58,000',
       '4,95,000', '6,99,000', '6,51,000', '6,51,000', '6,51,000',
       '6,51,000', '3,32,000', '3,71,000', '7,53,000', '11,17,000',
       '3,05,000', '9,45,000', '17,99,000', '6,81,000', '6,94,000',
       '3,28,000', '16,85,000', '6,27,000', '9,35,000', '9,10,000',
       '8,10,000', '6,50,000', '9,54,000', '7,46,000', '9,63,000',
       '7,84,000', '7,27,000', '10,71,000', '8,98,000', '10,40,000',
       '11,52,000', '5,96,000', '8,45,000', '8,16,000', '7,90,000',
       '10,63,000', '8,38,000', '6,63,000', '5,90,000', '8,38,000',
       '8,29,000', '7,99,000', '7,22,000', '9,56,000', '10,27,000',
       '7,36,000', '7,49,000', '6,91,000'], dtype=object)

Removing commas from the values in the price column so i can convert them to numbers for numerical computations

when possible, I turn values in to floats or intergers so thats it is less columns, when i turn categorical features
into T/F values, it creates many more columns.

In [97]:
df['Price'] = df['Price'].str.replace(",","")

Removiving 'BS' from the values in Emission columns and converting roman numerals to interger values for
the same purpose.

In [98]:
df['Emission'] = df['Emission'].str.replace("BS","")

In [99]:
df['Emission'] = df['Emission'].str.replace("IV", "4")

In [100]:
df['Emission'] = df['Emission'].str.replace("III", "3")

In [101]:
df['Emission'] = df['Emission'].str.replace("V", "5")

Changing values in the No_of_Owners column to numerical values from the same purpuse

In [102]:
df['No_of_Owners'] = df['No_of_Owners'].str.replace("1st", "0")

In [103]:
df['No_of_Owners'] = df['No_of_Owners'].str.replace("2nd", "1")

In [104]:
df['No_of_Owners'] = df['No_of_Owners'].str.replace("3rd", "2")

Telling the computer that the following columns are int or float

In [105]:
df['Emission'] = df['Emission'].astype(int)

In [106]:
df['Price'] = df['Price'].astype(int)

In [107]:
df['Mileage(kmpl)'] = df['Mileage(kmpl)'].astype(float)

In [108]:
df["No_of_Owners"] = df['No_of_Owners'].astype(int)

Looking a types of values to complete my data prep

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Car_Name               973 non-null    object
 1   Make                   973 non-null    object
 2   Model                  973 non-null    object
 3   Make_Year              973 non-null    int64
 4   Color                  973 non-null    object
 5   Body_Type              973 non-null    object
 6   Mileage_Run            973 non-null    int64
 7   No_of_Owners           973 non-null    int64
 8   Seating_Capacity       973 non-null    int64
 9   Fuel_Type              973 non-null    object
 10  Fuel_Tank_Capacity(L)  973 non-null    int64
 11  Engine_Type            973 non-null    object
 12  CC_Displacement        973 non-null    int64
 13  Transmission           973 non-null    object
 14  Transmission_Type      973 non-null    object
 15  Power(BHP)             973 non-null    float64
 16  Torque(Nm)             973 non-null    float64
 17  Mileage(kmpl)          973 non-null    float64
 18  Emission               973 non-null    int64
 19  Price                  973 non-null    int64
dtypes: float64(3), int64(8), object(9)
memory usage: 152.2+ KB

Looking at the distribution of values in the number of owners column

In [110]:
df['No_of_Owners'].value_counts()

0    816
1    153
2      4
Name: No_of_Owners, dtype: int64

Turning the catergorical variables into T/F values (columns with values of 1 or 0) which will be on scale with the numerical data

In [111]:
df_dummy = pd.get_dummies(df[['Car_Name', "Make", "Model", "Color", "Body_Type", "Fuel_Type", "Engine_Type", "Transmission", "Transmission_Type"]])

Looking at the beautiful dummy values I have made

In [112]:
df_dummy

,Car_Name_Chevrolet Beat [2009-2014] PS Petrol,Car_Name_Chevrolet Beat [2011-2014] LS Diesel,Car_Name_Chevrolet Beat [2014-2017] LS Diesel,Car_Name_Chevrolet Beat [2014-2017] LS Petrol,Car_Name_Chevrolet Cruze [2009-2017] LTZ AT,Car_Name_Datsun GO [2014-2019] T,Car_Name_Datsun Redi-GO [2015-2019] T (O),Car_Name_Ford EcoSport [2013-2015] Titanium 1.0L Ecoboost,Car_Name_Ford EcoSport [2013-2015] Titanium 1.5L TDCi,Car_Name_Ford EcoSport [2013-2015] Titanium 1.5L TDCi (Opt),...,Engine_Type_inline 4 cylinder petrol engine,Engine_Type_k14B VVT Engine,Engine_Type_mHawk Diesel Engine,Transmission_4-Speed,Transmission_5-Speed,Transmission_6-Speed,Transmission_7-Speed,Transmission_CVT,Transmission_Type_Automatic,Transmission_Type_Manual
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
969,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
970,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
971,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
972,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

Dropping  categorical features from the dataframe

In [113]:
df.drop(columns=['Car_Name', "Make", "Model", "Color", "Body_Type", "Fuel_Type", "Engine_Type", "Transmission", "Transmission_Type"], inplace=True)

creating a variable for the target feature

In [114]:
df_price = df['Price']

looking at the variable for target feature

In [115]:
df_price

0       657000
1       682000
2       793000
3       414000
4       515000
        ...
968     956000
969    1027000
970     736000
971     749000
972     691000
Name: Price, Length: 973, dtype: int64

re-organize the index column for the dataframe

In [116]:
df.drop('Price', axis=1,inplace=True)

In [117]:
# Here we are resetting the index of our price Dataframe to  adjust for standard scaler!
df_price = df_price.reset_index(drop=True)

In [118]:
df_price

0       657000
1       682000
2       793000
3       414000
4       515000
        ...
968     956000
969    1027000
970     736000
971     749000
972     691000
Name: Price, Length: 973, dtype: int64

Calling on the data frame to look at it

In [119]:
df

,Make_Year,Mileage_Run,No_of_Owners,Seating_Capacity,Fuel_Tank_Capacity(L),CC_Displacement,Power(BHP),Torque(Nm),Mileage(kmpl),Emission
0,2017,44611,0,5,45,1498,109.00,250.00,21.66,4
1,2016,20305,0,5,45,1197,82.00,115.00,17.19,5
2,2019,29540,1,5,40,1199,88.50,110.00,16.50,4
3,2017,35680,0,5,28,999,67.00,91.00,21.70,4
4,2017,25126,0,5,43,1197,81.86,113.75,18.90,5
...,...,...,...,...,...,...,...,...,...,...
968,2018,23869,0,5,43,1591,121.00,158.00,17.40,5
969,2019,14831,0,5,43,1591,121.00,158.00,17.40,5
970,2014,52846,0,5,43,1591,121.00,158.00,17.01,3
971,2020,28335,1,5,42,1499,98.96,215.00,18.50,5
972,2018,41176,0,5,32,1197,81.80,113.00,20.89,5

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Make_Year              973 non-null    int64
 1   Mileage_Run            973 non-null    int64
 2   No_of_Owners           973 non-null    int64
 3   Seating_Capacity       973 non-null    int64
 4   Fuel_Tank_Capacity(L)  973 non-null    int64
 5   CC_Displacement        973 non-null    int64
 6   Power(BHP)             973 non-null    float64
 7   Torque(Nm)             973 non-null    float64
 8   Mileage(kmpl)          973 non-null    float64
 9   Emission               973 non-null    int64
dtypes: float64(3), int64(7)
memory usage: 76.1 KB

Instantiating the Standar Scaler and fitting our Data Frame to it

In [121]:
# Instantiating our StandardScalar Object
ss = StandardScaler()

ss.fit(df)

df_scaled = ss.transform(df)

In [122]:
# Turning our StandardScalar object back into a dataframe, with the same column names as before 
df_scaled_new = pd.DataFrame(df_scaled, columns=df.columns)

In [123]:
df_scaled_new

,Make_Year,Mileage_Run,No_of_Owners,Seating_Capacity,Fuel_Tank_Capacity(L),CC_Displacement,Power(BHP),Torque(Nm),Mileage(kmpl),Emission
0,0.012776,0.126399,-0.432589,-0.213994,0.336894,0.711393,0.686235,1.585790,0.801409,-0.387205
1,-0.342384,-0.871579,-0.432589,-0.213994,0.336894,-0.375336,-0.363370,-0.437259,-0.865637,1.317548
2,0.723095,-0.492400,2.181755,-0.213994,-0.282762,-0.368116,-0.110687,-0.512187,-1.122966,-0.387205
3,0.012776,-0.240298,-0.432589,-0.213994,-1.769934,-1.090195,-0.946484,-0.796912,0.816326,-0.387205
4,0.012776,-0.673634,-0.432589,-0.213994,0.089032,-0.375336,-0.368813,-0.455991,-0.227908,1.317548
...,...,...,...,...,...,...,...,...,...,...
968,0.367935,-0.725245,-0.432589,-0.213994,0.089032,1.047159,1.152726,0.207119,-0.787319,1.317548
969,0.723095,-1.096336,-0.432589,-0.213994,0.089032,1.047159,1.152726,0.207119,-0.787319,1.317548
970,-1.052704,0.464519,-0.432589,-0.213994,0.089032,1.047159,1.152726,0.207119,-0.932766,-2.091957
971,1.078255,-0.541876,2.181755,-0.213994,-0.034899,0.715003,0.295937,1.061296,-0.377084,1.317548
972,0.367935,-0.014638,-0.432589,-0.213994,-1.274210,-0.375336,-0.371145,-0.467230,0.514244,1.317548

Combining hte data frame of our categorical variables back into the data frame after turning them into T/F (1/0) Values

In [124]:
df1 = pd.concat([df_scaled_new,df_dummy, df_price], axis = 1)

Calling on the new dataframe we have created to make sure everything looks good

In [125]:
df1

,Make_Year,Mileage_Run,No_of_Owners,Seating_Capacity,Fuel_Tank_Capacity(L),CC_Displacement,Power(BHP),Torque(Nm),Mileage(kmpl),Emission,...,Engine_Type_k14B VVT Engine,Engine_Type_mHawk Diesel Engine,Transmission_4-Speed,Transmission_5-Speed,Transmission_6-Speed,Transmission_7-Speed,Transmission_CVT,Transmission_Type_Automatic,Transmission_Type_Manual,Price
0,0.012776,0.126399,-0.432589,-0.213994,0.336894,0.711393,0.686235,1.585790,0.801409,-0.387205,...,0,0,0,0,0,1,0,1,0,657000
1,-0.342384,-0.871579,-0.432589,-0.213994,0.336894,-0.375336,-0.363370,-0.437259,-0.865637,1.317548,...,0,0,0,1,0,0,0,0,1,682000
2,0.723095,-0.492400,2.181755,-0.213994,-0.282762,-0.368116,-0.110687,-0.512187,-1.122966,-0.387205,...,0,0,0,1,0,0,0,0,1,793000
3,0.012776,-0.240298,-0.432589,-0.213994,-1.769934,-1.090195,-0.946484,-0.796912,0.816326,-0.387205,...,0,0,0,1,0,0,0,0,1,414000
4,0.012776,-0.673634,-0.432589,-0.213994,0.089032,-0.375336,-0.368813,-0.455991,-0.227908,1.317548,...,0,0,0,1,0,0,0,0,1,515000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,0.367935,-0.725245,-0.432589,-0.213994,0.089032,1.047159,1.152726,0.207119,-0.787319,1.317548,...,0,0,0,0,1,0,0,1,0,956000
969,0.723095,-1.096336,-0.432589,-0.213994,0.089032,1.047159,1.152726,0.207119,-0.787319,1.317548,...,0,0,0,0,1,0,0,1,0,1027000
970,-1.052704,0.464519,-0.432589,-0.213994,0.089032,1.047159,1.152726,0.207119,-0.932766,-2.091957,...,0,0,1,0,0,0,0,1,0,736000
971,1.078255,-0.541876,2.181755,-0.213994,-0.034899,0.715003,0.295937,1.061296,-0.377084,1.317548,...,0,0,0,1,0,0,0,1,0,749000
972,0.367935,-0.014638,-0.432589,-0.213994,-1.274210,-0.375336,-0.371145,-0.467230,0.514244,1.317548,...,0,0,0,1,0,0,0,1,0,691000

Creating variables for target feature and the data frame of other features in preparation for splitting
the data between training data and testing data

In [126]:
X = df1.drop('Price',axis=1)
y = df1['Price']

Splitting the data so that i have data to train the model and data to test the model with

In [127]:
X_train, X_test, y_train, y_test = train_test_split(
                                                X,
                                                y,
                                                test_size=0.2,
                                                random_state=42)

Creating a linear regression model, fitting it with training data and testing it with a program and
cross validating it.

In [128]:
lr = LinearRegression()
scores_lr = cross_validate(
                    lr, X_train, y_train, cv=5, 
                    return_train_score=True)
print(f"""train scores: {scores_lr['train_score']},
      test scores: {scores_lr['test_score']}""")

train scores: [0.99418695 0.9940379  0.99345253 0.99313692 0.99383978],
      test scores: [-5.04688798e+20 -2.55921133e+23 -7.00188928e+23 -2.29411695e+23
 -3.23709413e+23]

Creating a decision tree regression model, fitting it with training data and testing it with a program and
cross validating it to see if it performs better

In [129]:
dtr = DecisionTreeRegressor()
scores_dtr = cross_validate(
                    dtr, X_train, y_train, cv=5, 
                    return_train_score=True)
print(f"""train scores: {scores_dtr['train_score']},
      test scores: {scores_dtr['test_score']}""")

train scores: [1. 1. 1. 1. 1.],
      test scores: [0.86877083 0.91066327 0.94778266 0.91755147 0.94671191]

I have decided to use a decision tree regressor model since it has performed better on the cross validation. 
Now i am making a dummy model that just uses the mean values to see my improvement in the model that i create

In [130]:
from sklearn.dummy import DummyRegressor as dr

In [131]:
dr1 = dr()

In [132]:
dr1.fit(X_train, y_train)

DummyRegressor()

Looking at the dummy regressors predictions to make sure that it worked

In [133]:
dr1.predict(X_train)

array([745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152, 745221.07969152, 745221.07969152,
       745221.07969152, 745221.07969152])

Getting a preformace score with the dummy model to analyze the improvement of my modeling

In [134]:
dr1.score(X_train,y_train)

0.0

Creating my grid, which are the different options i can implement as my parameters for my DecisionTree Regressor
Model.

In [135]:
grid = {'criterion' : ['squared_error', 'friedman_mse', 'absolute_error', 'poisson'], 'splitter' : ['best', 'random'], 'min_samples_split' : [2,5,7]  }

Performing a GridSearch. The computer is running the data through a decision tree model with every possible combination of the grid parameters. It will also cross validate each time and return the parameters that create the best score.

In [136]:
gs= GridSearchCV(dtr, grid, verbose=3, n_jobs=-2)

In [137]:
gs.fit(X_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

[Parallel(n_jobs=-2)]: Using backend LokyBackend with 15 concurrent workers.
[Parallel(n_jobs=-2)]: Done   2 tasks      | elapsed:    1.3s
[Parallel(n_jobs=-2)]: Done 120 out of 120 | elapsed:    1.8s finished

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-2,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'min_samples_split': [2, 5, 7],
                         'splitter': ['best', 'random']},
             verbose=3)

Here I pull the best parameters from the Grid Search

In [138]:
gs.best_params_

{'criterion': 'friedman_mse', 'min_samples_split': 5, 'splitter': 'best'}

Creating a Model with the best parameters that I pulled from the grid search

In [139]:
best_dtr = DecisionTreeRegressor(criterion= 'friedman_mse', min_samples_split =  7, splitter= 'best')

Cross Validating this model to see the improvement from the baseline model

In [140]:
scores_best_dtr = cross_validate(
                    best_dtr, X_train, y_train, cv=5, 
                    return_train_score=True)
print(f"""train scores: {scores_best_dtr['train_score']},
      test scores: {scores_best_dtr['test_score']}""")

train scores: [0.99229683 0.99320439 0.9906468  0.99214798 0.99060832],
      test scores: [0.71567538 0.88213938 0.95142906 0.93386102 0.94339344]

Fitting the training data to my new model

In [147]:
best_dtr.fit(X_train,y_train)

DecisionTreeRegressor(criterion='friedman_mse', min_samples_split=7)

In [154]:
y_pred = best_dtr.predict(X_test)
y_pred

array([ 347833.33333333,  465833.33333333,  662000.        ,
        662000.        , 1900000.        , 1207750.        ,
        426500.        ,  538833.33333333,  540000.        ,
       1576000.        ,  680600.        ,  607200.        ,
       1314000.        ,  810600.        ,  636000.        ,
        792333.33333333,  680200.        ,  894666.66666667,
        290000.        ,  307000.        , 1085000.        ,
        490500.        ,  946166.66666667,  484333.33333333,
        782800.        ,  562000.        , 1051000.        ,
        339400.        ,  820000.        ,  423000.        ,
        635500.        ,  287500.        ,  437000.        ,
        749000.        ,  763500.        ,  749000.        ,
        776600.        ,  435000.        ,  608400.        ,
        426500.        ,  626666.66666667,  439000.        ,
        334500.        , 1092000.        , 1047000.        ,
        914000.        ,  538833.33333333,  569200.        ,
       1424000.        , 1183666.66666667,  470500.        ,
       1751600.        ,  863166.66666667,  776600.        ,
        749666.66666667,  367500.        ,  636000.        ,
        539000.        ,  569200.        , 1183666.66666667,
        347833.33333333,  470500.        ,  754000.        ,
        657000.        ,  374000.        , 1019500.        ,
       1900000.        ,  569200.        ,  983500.        ,
        347833.33333333,  511166.66666667,  708750.        ,
       1186000.        ,  334500.        ,  820000.        ,
       1751600.        , 1085000.        ,  650666.66666667,
        539000.        ,  417800.        ,  767500.        ,
        374000.        ,  650666.66666667,  844000.        ,
        374000.        ,  538833.33333333,  367500.        ,
        767500.        ,  983500.        ,  627333.33333333,
        702000.        ,  659500.        ,  758333.33333333,
       1005500.        ,  356000.        ,  931500.        ,
        307000.        , 1706400.        ,  323000.        ,
        607200.        ,  391200.        ,  776600.        ,
        753333.33333333, 1019000.        ,  607200.        ,
        367500.        ,  627333.33333333,  540666.66666667,
        323000.        ,  761750.        ,  788500.        ,
        485800.        ,  382500.        ,  881000.        ,
        598250.        ,  844000.        ,  983500.        ,
        961000.        ,  781000.        ,  397666.66666667,
        511166.66666667,  680600.        ,  680200.        ,
       1087750.        ,  671200.        , 1991666.66666667,
        417800.        ,  651666.66666667,  657000.        ,
        810600.        ,  556800.        ,  465833.33333333,
        567000.        ,  569200.        ,  680600.        ,
        818500.        ,  607200.        , 1576000.        ,
        646666.66666667,  680600.        ,  931500.        ,
        347833.33333333,  946166.66666667,  438250.        ,
        671200.        , 1076000.        ,  627333.33333333,
       1087750.        ,  786750.        ,  485800.        ,
        611000.        ,  749666.66666667,  407750.        ,
        606833.33333333, 1822000.        ,  569200.        ,
        367500.        , 1092000.        ,  437000.        ,
        317833.33333333,  792333.33333333,  612000.        ,
        761750.        ,  437000.        ,  540000.        ,
        749666.66666667, 1129000.        ,  636000.        ,
        810600.        ,  662000.        , 1092000.        ,
        367500.        , 1991666.66666667,  680200.        ,
        452000.        , 1186000.        ,  782800.        ,
        908500.        ,  894666.66666667,  749666.66666667,
        485800.        ,  590166.66666667,  677250.        ,
        538833.33333333,  277200.        ,  720000.        ,
        671200.        , 1075200.        ,  307000.        ,
        680600.        ,  514000.        ,  539000.        ,
        713500.        ,  483666.66666667,  427000.        ])

In [155]:
Comparison_df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
Comparison_df

     Real Values  Predicted Values
199       336000      3.478333e+05
538       461000      4.658333e+05
174       547000      6.620000e+05
464       684000      6.620000e+05
66       1742000      1.900000e+06
..           ...               ...
578       485000      5.140000e+05
327       498000      5.390000e+05
878       617000      7.135000e+05
849       430000      4.836667e+05
801       454000      4.270000e+05

[195 rows x 2 columns]